//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A28
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int Student_id { get; set; }
        public string Student_Name { get; set; }
        public string Student_Desp { get; set; }
        public Nullable<int> phone_number { get; set; }
    }
}
