// <auto-generated />
namespace EmployeeManagementSystemApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Columnnamechange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Columnnamechange));
        
        string IMigrationMetadata.Id
        {
            get { return "201904081157370_Column name change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
