// <auto-generated />
namespace Assignment_06_A11_1_SP_EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class kl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kl));
        
        string IMigrationMetadata.Id
        {
            get { return "201907290329380_kl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
