//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> StudioID { get; set; }
        public string Role { get; set; }
    
        public virtual Studio Studio { get; set; }
    }
}
