CREATE DATABASE GLOBANT_EMPLOYEE_SYSTEM ;

USE GLOBANT_EMPLOYEE_SYSTEM;

CREATE TABLE STUDIOS(STUDIO_ID INT PRIMARY KEY, STUDIO_NAME VARCHAR(10),STUDIO_DESCRIPTION VARCHAR(50));

CREATE TABLE PROJECTS(PROJECT_CODE INT IDENTITY(1,1) PRIMARY KEY ,PROJECT_NAME VARCHAR(50),STUDIO_ID INT FOREIGN KEY REFERENCES STUDIOS(STUDIO_ID));

CREATE TABLE EMPLOYEE(EMPLOYEE_ID INT IDENTITY(1,1) PRIMARY KEY, F_NAME VARCHAR(10),L_NAME VARCHAR(10),LOCATION  VARCHAR(30),MOBILE_NO VARCHAR(12),DOB VARCHAR(20), EMAIL VARCHAR(30),PROJECT_CODE INT FOREIGN KEY REFERENCES PROJECTS(PROJECT_CODE));

CREATE TABLE EMPLOYEE_PROJECTS_MAPPING (EMPLOYEE_PROJECTS_MAPPING_ID INT IDENTITY(1,1) PRIMARY KEY ,EMPLOYEE_ID INT FOREIGN KEY REFERENCES EMPLOYEE(EMPLOYEE_ID), PROJECT_CODE INT FOREIGN KEY REFERENCES PROJECTS(PROJECT_CODE));



Select * from EMPLOYEE

Select * from PROJECTS

Select * from STUDIOS

Select * from EMPLOYEE_PROJECTS_MAPPING

Insert into EMPLOYEE(F_NAME,L_NAME,LOCATION,MOBILE_NO,DOB,EMAIL,PROJECT_CODE) Values('Aarti','Chilka' ,'Pune','1234567897','1996','aarti@gmail.com','3')

Insert into EMPLOYEE(F_NAME,L_NAME,LOCATION,MOBILE_NO,DOB,EMAIL,PROJECT_CODE) Values('Chetan','Bavaskar' ,'Pune','1234567897','1994','chetan@gmail.com','2')

Insert into EMPLOYEE(F_NAME,L_NAME,LOCATION,MOBILE_NO,DOB,EMAIL,PROJECT_CODE) Values('Pooja','Mhaske' ,'BAnglore','1234567897','1996','aarti@gmail.com','1')

Insert into EMPLOYEE(F_NAME,L_NAME,LOCATION,MOBILE_NO,DOB,EMAIL,PROJECT_CODE) Values('Shubham','Yadav' ,'Pune','1234567897','1993','aarti@gmail.com','3')

Insert into STUDIOS values ('3','QE','Quality Engineering Studios')


Insert into EMPLOYEE(F_NAME,L_NAME,LOCATION,MOBILE_NO,DOB,EMAIL) Values('Sanket','Ganjave' ,'Pune','1234567897','1990','sanket@gmail.com')

Select F_Name,L_NAME,LOCATION,MOBILE_NO,DOB,EMAIL,e.PROJECT_CODE,PROJECT_NAME,STUDIO_NAME from EMPLOYEE e INNER JOIN PROJECTS p ON 
 e.PROJECT_CODE = p.PROJECT_CODE INNER JOIN STUDIOS s ON p.STUDIO_ID = s.STUDIO_ID where EMPLOYEE_ID = 4


Select F_Name,L_NAME,LOCATION,MOBILE_NO,DOB,EMAIL,e.PROJECT_CODE,PROJECT_NAME,STUDIO_NAME from EMPLOYEE e Full OUTER JOIN PROJECTS p ON 
 e.PROJECT_CODE = p.PROJECT_CODE Full Outer JOIN STUDIOS s ON p.STUDIO_ID = s.STUDIO_ID 

Select F_Name,L_NAME,LOCATION,MOBILE_NO,DOB,EMAIL,e.PROJECT_CODE,PROJECT_NAME,STUDIO_NAME from EMPLOYEE e left OUTER JOIN PROJECTS p ON 
 e.PROJECT_CODE = p.PROJECT_CODE left Outer JOIN STUDIOS s ON p.STUDIO_ID = s.STUDIO_ID

 Select F_Name,L_NAME,LOCATION,MOBILE_NO,DOB,EMAIL,e.PROJECT_CODE,PROJECT_NAME,STUDIO_NAME from EMPLOYEE e Right OUTER JOIN PROJECTS p ON 
 e.PROJECT_CODE = p.PROJECT_CODE Right Outer JOIN STUDIOS s ON p.STUDIO_ID = s.STUDIO_ID
 
 
